"""Replace stale v4 model rows and register v4.3 parameters with provenance."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


MODEL_LAYERS = {"model", "physics", "validation", "uncertainty", "applicability", "condition", "mechanism_proxy"}
RDKit_DOCS = "RDKit 2025.09.6 official documentation; https://www.rdkit.org/docs/"
TARGET = "Target article and SI; DOI 10.1021/acs.orglett.5c05116"


def row(parameter, layer, data_type, definition, unit_or_values, source, model_use, limitation):
    return {
        "parameter": parameter,
        "layer": layer,
        "data_type": data_type,
        "definition": definition,
        "unit_or_values": unit_or_values,
        "source": source,
        "model_use": model_use,
        "limitation": limitation,
    }


NEW_ROWS = [
    row("yield_algorithm", "model", "categorical", "Final yield estimator", "Ridge regression", "Nested grouped candidate comparison over 26 in-domain rows", "candidate ranking", "Nested advantage over the mean baseline is not statistically established"),
    row("yield_alpha", "model", "numeric", "Ridge L2 penalty", "30", "Selected inside grouped validation", "yield hyperparameter", "Selection can change with additional families"),
    row("yield_feature_set", "model", "list", "Active generated feature names", "mol_logp; mol_tpsa; mol_fraction_csp3; mol_rotatable_bonds; mol_bertz_complexity; mol_heteroatoms; nitrile_count", f"{RDKit_DOCS}; generated by compute_mechanism_descriptors.py", "primary yield model", "2D empirical descriptors are not transition-state or quantum descriptors"),
    row("yield_target_transform", "physics", "formula", "logit transform with clipping before fitting and inverse-logit on output", "dimensionless", "Bounded-response model implementation in train_v43.py", "keeps yield predictions in [0,100]", "Does not model assay censoring in the scope table"),
    row("yield_manual_fallback", "model", "categorical", "Fallback when a user has not supplied precomputed RDKit descriptors", "RBF kernel Ridge on manual_core", "Grouped candidate comparison; artifact fallback_models", "manual web form only", "Lower information content than the primary generated-descriptor model"),
    row("ee_algorithm", "model", "categorical", "Final ee estimator", "RBF kernel Ridge", "Nested grouped candidate comparison over 26 in-domain rows", "local ee ranking", "2n remains an unresolved high-influence exception"),
    row("ee_alpha", "model", "numeric", "Kernel Ridge regularization", "0.1", "Selected inside grouped validation", "ee hyperparameter", "Small-n selection uncertainty"),
    row("ee_gamma", "model", "numeric", "RBF kernel width parameter", "0.1", "Selected inside grouped validation", "ee hyperparameter", "Small-n selection uncertainty"),
    row("ee_feature_set", "model", "list", "Active curated feature names", "aryl_rings; fused_aromatic; cyclic_center; alpha_chain_carbons; ortho_sub_count; hammett_sigma_mp; sidechain_polar_count; meta_sub_count; para_sub_count; halogen_count; edg_count; ewg_count", TARGET, "ee model", "Expert-coded counts do not resolve conformers or catalyst-substrate geometry"),
    row("ee_transform", "physics", "formula", "DeltaDeltaG = RT ln((1+ee)/(1-ee))", "kcal/mol", "Thermodynamic selectivity relation at 298.15 K", "bounded selectivity target", "Reported ee is treated as an effective selectivity ratio"),
    row("nested_group_mae_yield", "validation", "numeric", "Outer chemical-family grouped MAE", "8.029 percentage points", "validation_metrics.csv", "honest workflow estimate", "26 rows from one paper; CI includes no advantage over mean baseline"),
    row("nested_group_mae_ee", "validation", "numeric", "Outer chemical-family grouped MAE", "6.180 percentage points", "validation_metrics.csv", "honest workflow estimate", "Maximum error is 45.207 points at 2n"),
    row("cross_conformal_half_width_yield", "uncertainty", "numeric", "Empirical cross-conformal half-width from nested out-of-group residuals", "20.964 percentage points", "model_artifact_v43.json", "screening interval", "Not strict split-conformal coverage; prospective coverage unknown"),
    row("cross_conformal_half_width_ee", "uncertainty", "numeric", "Empirical cross-conformal half-width from nested out-of-group residuals", "23.112 percentage points", "model_artifact_v43.json", "screening interval", "Not strict split-conformal coverage; prospective coverage unknown"),
    row("nearest_distance", "applicability", "numeric", "Nearest standardized Euclidean distance in manual_core feature space", "dimensionless", "26-row training domain", "domain grading", "Cannot detect every mechanistic change"),
    row("nearest_distance_q90", "applicability", "numeric", "LOO nearest-neighbour warning threshold", "0.722501", "applicability_calibration.csv", "warn boundary", "Empirical and data-set dependent"),
    row("nearest_distance_q95", "applicability", "numeric", "LOO nearest-neighbour refusal threshold", "1.015943", "applicability_calibration.csv", "distance refusal", "Type and pathway gates remain authoritative"),
    row("strong_para_ewg_rule", "applicability", "rule", "Refuse new ee point prediction when sigma >= 0.60 and para_sub_count >= 1", "REFUSE", "Observed 2n exception and lack of same-subdomain replicates", "prevents unsupported extrapolation", "Rule is conservative and must be revisited after prospective examples"),
    row("condition_multifactor_gate", "applicability", "rule", "Refuse more than one simultaneous screened-factor change", "max 1", "Target SI uses matched one-factor screens", "condition evidence layer", "Does not substitute for factorial optimization"),
    row("gasteiger_charge_family", "mechanism_proxy", "numeric", "Reaction-centre, nitrile-carbon, aryl-attachment and maximum absolute Gasteiger charges", "e", "Gasteiger and Marsili, Tetrahedron 1980, DOI 10.1016/0040-4020(80)80168-2; RDKit", "candidate feature testing", "Empirical partial-charge proxy, not NBO/DFT charge"),
    row("crippen_descriptor_family", "mechanism_proxy", "numeric", "Molecular and reaction-centre Crippen logP/MR quantities", "dimensionless or molar refractivity", "Wildman and Crippen, J. Chem. Inf. Comput. Sci. 1999, DOI 10.1021/ci990307l; RDKit", "candidate feature testing", "Fragment estimates, not measured partitioning or polarizability"),
    row("mol_tpsa", "mechanism_proxy", "numeric", "Topological polar surface area", "angstrom squared", "Ertl et al., J. Med. Chem. 2000, DOI 10.1021/jm000942e; RDKit", "primary yield feature", "2D topological approximation"),
    row("topological_complexity_family", "mechanism_proxy", "numeric", "Fraction Csp3, rotatable bonds, Bertz complexity, atom counts and local graph distances", "mixed; see CSV headers", RDKit_DOCS, "candidate feature testing", "Topology does not encode solution conformations"),
    row("solvent_dielectric_constant", "condition", "numeric", "Room-temperature relative permittivity reference value", "dimensionless", "Reichardt and Welton, DOI 10.1002/9783527632220", "condition similarity audit", "Not measured in the reaction mixture; MTBE source remains lower confidence"),
    row("solvent_reichardt_et30", "condition", "numeric", "Reichardt ET(30) polarity", "kcal/mol", "Reichardt and Welton, DOI 10.1002/9783527632220; cross-check DOI 10.1021/acsomega.9b03880", "condition similarity audit", "Not an independently learned solvent effect"),
    row("condition_identity_features", "condition", "categorical", "One-hot solvent, photocatalyst class, Cu source and ligand identity; nominal Cu oxidation state", "categorical", TARGET, "auditable condition vectors", "33 sparse matched-control rows do not support arbitrary combinations"),
]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    old = pd.read_csv(args.input)
    replacement_names = {record["parameter"] for record in NEW_ROWS}
    retained = old[
        ~old["layer"].astype(str).isin(MODEL_LAYERS)
        & ~old["parameter"].astype(str).isin(replacement_names)
    ].copy()
    updated = pd.concat([retained, pd.DataFrame(NEW_ROWS)], ignore_index=True)
    if updated["parameter"].duplicated().any():
        duplicates = updated.loc[updated["parameter"].duplicated(), "parameter"].tolist()
        raise ValueError(f"Duplicate parameters: {duplicates}")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    updated.to_csv(args.output, index=False, encoding="utf-8-sig")
    print(f"Wrote {len(updated)} current parameter records to {args.output}")


if __name__ == "__main__":
    main()
